- hosts: "*"

  # Name of the playbook
  name: provision-sintaxlab

  # Make it so that Ansible can "escalate" to root
  # (i.e. run commands using sudo)
  become: true

  # ============================================ #
  # VARIABLES                                    #
  # ============================================ #

  vars:
    local_storage: "/opt/ansible/storage"

  # ============================================ #
  # TASKS                                        #
  # ============================================ #

  tasks:

    # ---------------------------------------------- #

    - name: Update Server Packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Git and Pip
      apt:
        name:
          - git
          - python3-pip
        state: latest

    # ---------------------------------------------- #

    - name: Install Pyenv Dependencies
      apt:
        name:
          - make
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - wget
          - curl
          - llvm
          - libncurses5-dev
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libffi-dev
          - liblzma-dev
        state: latest

    - name: Install Pyenv
      shell: >
        curl https://pyenv.run | bash
      args:
        creates: "~/.pyenv"
    
    - name: Add Pyenv to Bashrc
      lineinfile:
        path: ~/.bashrc
        state: present
        create: yes
        line: "{{ item }}"
      with_items:
        - 'export PYENV_ROOT="$HOME/.pyenv"'
        - 'export PATH="$PYENV_ROOT/bin:$PATH"'
        - 'eval "$(pyenv init -)"'
        - 'eval "$(pyenv virtualenv-init -)"'

    - name: Install Python 3.9.13 and Set as Global Version
      shell: |
        ~/.pyenv/libexec/pyenv install 3.9.13
        ~/.pyenv/libexec/pyenv global 3.9.13
      args:
        creates: "~/.pyenv/versions/3.9.13"

    # -------------------------------------------- #

    # Note: Use the HTTPS URL for the Git Repo in order to avoid the use of SSH Keys
    # Also use the "force" option to discard any local changes to the repo.
    - name: Clone the "HormoziGPT" Repo
      git:
        repo: https://github.com/wombyz/HormoziGPT.git
        dest: ~/HormoziGPT
        force: yes

    - name: Install Requirements for the "HormoziGPT" Repo
      pip:
        requirements: ~/HormoziGPT/requirements.txt 
    
    - name: Copy Environment Variables (.env)
      copy:
        src: "{{ local_storage }}/.env"
        dest: ~/HormoziGPT/.env
        mode: "0777"

    # For this line to properly work your environment variables in the .env file
    # must be in the format "VAR_NAME=VAR_VALUE". Dont use spaces around the "=" sign.
    - name: Add Environment Variables in .env to Bashrc
      lineinfile:
        path: ~/.bashrc
        state: present
        create: yes
        line: "{{ item }}"
      with_items:
        - 'export $(cat ~/HormoziGPT/.env | xargs)'

